---
volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres:13.15-alpine
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aluno