PUT {{address}}/academico/alunos/1
Content-Type: application/json
Accept: application/json

{
  "nome": "Ana Clara",
  "sexo": "F",
  "dt_nasc": "2020-08-13"
}

>> responses/aluno-update-1-{{$timestamp}}.json