POST {{address}}/academico/alunos
Content-Type: application/json
Accept: application/json

{
  "nome": "João ",
  "sexo": "M",
  "dt_nasc": "2011-10-20"
}

>> responses/aluno-insert-{{$timestamp}}.json